# Generated by Django 5.0.1 on 2024-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosetClothes',
            fields=[
                ('clothes_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('add_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'closet_clothes',
                'managed': False,
            },
        ),
    ]
