# Generated by Django 5.0.1 on 2024-01-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllOutfits',
            fields=[
                ('outfit_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alloutfits',
                'managed': False,
            },
        ),
    ]
