# Generated by Django 5.0.1 on 2024-02-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('outfit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitClothes',
            fields=[
                ('outfit_clothes_id', models.AutoField(primary_key=True, serialize=False)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.closetclothes')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
            ],
        ),
        migrations.DeleteModel(
            name='AllOutfits',
        ),
        migrations.AddField(
            model_name='outfit',
            name='clothes',
            field=models.ManyToManyField(through='outfit.OutfitClothes', to='closet.closetclothes'),
        ),
    ]
