# Generated by Django 5.0.1 on 2024-02-02 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0003_outfit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfitclothes',
            old_name='outfit_clothes_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='AllOutfits',
            fields=[
                ('all_outfit_id', models.AutoField(primary_key=True, serialize=False)),
                ('outfit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
