# Generated by Django 5.0.1 on 2024-02-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0004_rename_outfit_clothes_id_outfitclothes_id_alloutfits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alloutfits',
            old_name='outfit_id',
            new_name='outfit',
        ),
        migrations.RenameField(
            model_name='alloutfits',
            old_name='user_id',
            new_name='user',
        ),
    ]
