# Generated by Django 5.0.1 on 2024-02-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0005_rename_outfit_id_alloutfits_outfit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllOutfits',
        ),
    ]
