# Generated by Django 5.0.1 on 2024-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
                ('dob', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
